# Generated by Django 3.2 on 2023-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230322_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Short',
        ),
    ]
